# NAME: Justin Hong, Kedar Thiagarajan
# EMAIL: justinjh@ucla.edu, kedarbt@ucla.edu
# ID: 604565186, 504539433

.SILENT:

default:

dist:
	tar -czf lab3b-604565186.tar.gz lab3b.py lab3b Makefile README 

clean: