# NAME: Justin Hong, Kedar Thiagarajan
# EMAIL: justinjh@ucla.edu, kedarbt@ucla.edu
# ID: 604565186, 504539433

default:
	gcc -o lab3a lab3a.c -lm

dist:
	tar -czf lab3a-604565186.tar.gz lab3a.c Makefile README ext2_fs.h

clean:
	rm -f lab3a